spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    #driverClassName: oracle.jdbc.OracleDriver
    #driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #driverClassName: org.postgresql.Driver
    druid:
      url: jdbc:mysql://49.235.55.199:3306/redCloud_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&nullCatalogMeansCurrent=true
      username: root
      password: jihongyun
#      url: jdbc:oracle:thin:@192.168.10.10:1521:helowin
#      username: renren
#      password: 123456
#      url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=security_enterprise_general
#      username: sa
#      password: 123456
#      url: jdbc:postgresql://192.168.10.10:5432/security_enterprise_general
#      username: postgres
#      password: 123456
      #多数据源的配置，需要引用renren-datasources
#      multi:
#        first:
#          url: jdbc:mysql://localhost:3306/security_enterprise_general?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#          username: renren
#          password: 123456
#        second:
#          url: jdbc:mysql://localhost:3306/security_enterprise_general?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#          username: renren
#          password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
          enabled: true
        wall:
#          config:
#            multi-statement-allow: true
          enabled: true
      web-stat-filter:
        enabled: true
      # 开启 Aop 监控
#      aop-stat:
#        enabled: true