# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8082
    context-path: /redCloud-api-generator

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-2zeyx7cweepz1s71xuo.mysql.rds.aliyuncs.com:3306/alipayapp1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: shazam
        password: Shazam@520
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

